sudo: required # or false
language: python

python:
    - 2.7
      #- 3.5
os: trusty
env:
    - YAMBO_VERSION=4.1 PW_VERSION=5.4
#    - any combination of versions

matrix:
    allow_failures:
        - python: 3.5 # Builds using this version can fail without compromising the end result
    fast_finish: true # Don't wait for the test on Py3.5 to finish to ack
# Add to the matrix of jobs
#    - os: osx
#      language: objective-c
#      env: PYENV_VERSION=2.7.12
#    - os: osx
#      language: objective-c
#      env: PYENV_VERSION=3.5.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran libopenmpi-dev openmpi-bin libblas-dev liblapack-dev libfftw3-dev libnetcdf-dev libhdf5-serial-dev

install:
  - "pip install -r ./tests/requirements.txt"
  - "./tests/install.sh"
  - "python setup.py install"
script:
    - "python ./tests/test_si.py -f"

# safelist
branches:
  only:
    - travis

deploy:
    skip_cleanup: true
