sudo: false # or required
language: python

python:
    - 2.7
      #- 3.5
os: trusty
env:
    - YAMBO_VERSION=4.1 PW_VERSION=5.4
#    - any combination of versions

matrix:
    allow_failures:
        - python: 3.5 # Builds using this version can fail without compromising the end result
    fast_finish: true # Don't wait for the test on Py3.5 to finish to ack
# Add to the matrix of jobs
#    - os: osx
#      language: objective-c
#      env: PYENV_VERSION=2.7.12
#    - os: osx
#      language: objective-c
#      env: PYENV_VERSION=3.5.2

addons:
    apt:
        packages:
            - gfortran
            - libopenmpi-dev
            - openmpi-bin
            - libblas-dev
            - liblapack-dev
            - libfftw3-dev
            - libnetcdf-dev
            - libhdf5-serial-dev

after_success:
  - "which gfortran"
  - "sudo apt-get install time -qq -y"
  - "which time"
  - "pip install -r ./tests/requirements.txt"
  - "./tests/install.sh -y YAMBO_VERSION -pw PW_VERSION"
#script:
#    - "python ./tests/test_si.py -f"

# safelist
branches:
  only:
    - travis

deploy:
    skip_cleanup: true
